sudo: required
dist: trusty

services:
  - docker

#before steps before deploying project
before_install:
  - docker build -t sumanth/dockeraws -f Dockerfile.dev .

#just for running the test coverage not impo similar to sonarqube
script:
  - docker run -e CI=true sumanth/dockeraws npm run test --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2"

  app: "simple-docker-aws"
  env: "Simpledockeraws-env"


  bucket: "elasticbeanstalk-us-east-2-033521689035"
  bucket_path: "simple-docker-aws"
  on:
    branch: master
  access_key_id: "AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


  
