sudo: required
dist: trusty

services:
  - docker

#before steps before deploying project
before_install:
  - docker build -t sumanth/dockeraws -f Dockerfile.dev .

#just for running the test coverage not impo similar to sonarqube
script:
  - docker run -e CI=true sumanth/dockeraws npm run test --coverage

deploy:
  provider: elasticbeanstalk 
  region: "us-east-2"
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  app: "simple-docker-aws"
  env: "Simpledockeraws-env"


  bucket_name: "elasticbeanstalk-us-east-2-033521689035"
  bucket_path: "simple-docker-aws"
  on:
    branch: master
  skip_cleanup: true

after_deploy:
  - echo "deployment done!!!"


  
